### PR TITLE
Monthly

### PR DESCRIPTION
**Pull request by nemchik**
- [x] Add `.editorconfig` files to the root of all container image projects. This file follows our internally discussed coding guidelines.
- [x] Remove microbadger badges from readmes as the service will shut down on July 1st
- [x] Remove external and package trigger workflows when deprecation flag is set to true https://github.com/linuxserver/docker-jenkins-builder/pull/113
- [x] Fix deletion of old templates (wrong folder used)
- [x] Fix deletion on deprecation
- [x] Adjust contribution wording about typos https://github.com/linuxserver/docker-jenkins-builder/pull/112

### CODE REVIEW

**Comment by nemchik** [comment]
Note: I did a search for any existing `.editorconfig` files across our org https://github.com/search?q=org%3Alinuxserver+filename%3A.editorconfig&type=code

None of those exist anywhere that would be affected by adding `.editorconfig` files to container image projects (repos that run the builder). We will not be able to override the `.editorconfig` files in the root of any given project. We can add `.editorconfig` files in subfolders to override behavior inside those subfolders.

**Comment by Roxedus** [comment]
What does `Fix deletion on deprecation` mean in this context?

**Comment by aptalca** [comment]
`git rm` of files was broken when deprecation but was set. My quick patch fixed it

**Comment by nemchik** [comment]
> - [ ] Add [logging functions](https://github.com/github/super-linter/blob/master/lib/functions/log.sh) to Jenkinsfile (and possibly other places, expand on this description if needed)

Will be moved to an independent PR

**Comment by nemchik** [comment]
This should be ready to merge after https://github.com/linuxserver/docker-jenkins-builder/pull/113 merges

**Review by Roxedus — APPROVED** [review]

**Review by aptalca — APPROVED** [review]

**Pull request merged**
