### PR TITLE
Monthly

### PR DESCRIPTION
**Pull request by thelamer**
Pushes a new meta image as version-"external version number" also fixes a bug for new repos that killed off the build if it is an initial project. Closes #50

### CODE REVIEW

**Comment by onedr0p** [comment]
Do you think it's possible to drop `version-` from the image tag? Thus making the tag the real actual application version?

**Comment by onedr0p** [comment]
@thelamer @Roxedus @aptalca any thoughts about my comment above?

**Comment by RealOrangeOne** [comment]
@onedr0p my original PR didn't have it, I agree with the idea. `version` seems unnecessary, as the tags are already used to convey version. I also believe this change will add it 

(PS: Tagging lots of people in a PR like that isn't a constructive way of getting answers)

**Comment by onedr0p** [comment]
@RealOrangeOne If you look at the changes, this will add a `version-` prefix to the tags.

**Comment by RealOrangeOne** [comment]
Woops, comment wasn't clear enough.
> @onedr0p my original PR (#50) didn't have it, I agree that it's unnecessary to have.

**Comment by thelamer** [comment]
Yeah the version- is a cma thing for repos that may have tag collision.

**Comment by RealOrangeOne** [comment]
I'd be interested in confirming if any actually have a collision in version numbers. Feels like a lot of noise and mess around tags for a potentially unnecessary precaution. 99% of projects are using semver anyway, which won't conflict.

**Comment by onedr0p** [comment]
hm, does that mean you do not want to tag without the prefix `version-`?

Having tag collision is fine for the semver tags, they will get overwritten which is what we'd like. This is no different than overriding the `latest` tags.

**Comment by thelamer** [comment]
In the end it can be any string concatted, but the version tag cannot just be the external version number we don't control it.

**Comment by onedr0p** [comment]
I am still lost, for projects with git tags, you are pulling the tags from the projects git repo and git does not allow duplicate tags.

What exactly are you worried about with _tag collision_?

**Review by aptalca — APPROVED** [review]

**Pull request merged**
