### PR TITLE
Monthly April

### PR DESCRIPTION
**Pull request by thelamer**
This is a rolling Pull request so we can gradually add changes to the build logic throughout the month. 

At the end of this cycle we will create a full loop test of this current template logic on an isolated branch confirm functionality and merge this to master.

### CODE REVIEW

**Comment by CHBMB** [comment]
Had a look at this one @thelamer bit beyond me I'm afraid.....

**Comment by aptalca** [comment]
Transferring notes from nextcloud:

I gave a lot of thought to replacing the package update related build exit, to prevent double builds. My idea was to have the build continue after committing to master the new package_versions.var and push to the hub, and also make sure the new build job immediately exited if the master commit was a package_versions update commit. Later I realized that this would break replaying of a failed build. In that case, let’s say a package check build sees a difference in package versions, commits the new package_versions.var, continues on to push to the hub. If the push is unsuccessful and we replay the whole build, this time it won’t notice a difference in package versions because the var file on github is already updated and there will be no push.

**Comment by aptalca** [comment]
Also, in Ubuntu and alpine baseimages, we can replace `COPY qemu-aarch64-static /usr/bin` with `ADD https://lsio-ci.ams3.digitaloceanspaces.com/qemu-aarch64-static /usr/bin`, and remove the curling of the qemu bits in Jenkinsfiles altogether. That way any user building the baseimage can do so locally, without having to manually download the qemu bits.

**Comment by thelamer** [comment]
What should we guard with? The commit message? We need to be able to handle when only the external version changes. 

As for base images and Qemu, I agree but instead of a layer we can just curl it in during build in the RUN logic https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile.aarch64#L53

**Comment by aptalca** [comment]
Yeah, I just wanted to document my goal and the issue I ran into. Don't have a good solution unfortunately.

With regards to qemu, yup, I agree curling in RUN is better as it saves a layer.

**Pull request merged**
