### PR TITLE
Update deprecation for v3, disable future builds

### PR DESCRIPTION
**Pull request by aptalca**
- Fixed existing bug that prevented workflow deletion during deprecation if updated templates were pushed
- Added s6v3 detection for deprecation
- For s6v3, it creates the necessary files and folders to add and enable `init-deprecate`, sandwiched between `init-config-end` and `init-services`
- Adds a build disabling stage to the end of the Jenkinsfile if deprecation var is set. The stage only runs if a deprecation build is successfully pushed to the hubs. The stage deletes the Jenkinsfile and commits to the repo, effectively disabling all future jenkins builds for that branch.
- [feature creep] make the readme truncation message on docker hub more prominent (something I've been meaning to fix for a long time)

### CODE REVIEW

**Comment by thespad** [comment]
We should really add the deprecation step to the `user2` bundle, probably just before the CI output, so it runs at the end of the init and doesn't get swallowed up by any other output.

IIRC the existing deprecation message gets added as `98`

**Comment by aptalca** [comment]
Moved it in between `init-config-end` and `init-services`. The service log output will flood in some containers, but this way it runs by itself so the deprecation message doesn't get split up by other messages, redering it unreadable.

**Comment by thespad** [comment]
We should probably update the deprecation file itself too to match the newer init formatting.

**Comment by aptalca** [comment]
just shellcheck?

**Comment by thespad** [comment]
I was thinking something like

```bash
#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo '
╔════════════════════════════════════════════════════╗
╠════════════════════════════════════════════════════╣
║                                                    ║
║             This image is deprecated.              ║
║      We will not offer support for this image      ║
║            and it will not be updated.             ║
║                                                    ║
╠════════════════════════════════════════════════════╣
╚════════════════════════════════════════════════════╝
{% if project_deprecation_message is defined %}

{{ project_deprecation_message | regex_replace('\'','\\\'') }}

══════════════════════════════════════════════════════{% endif %}'
```

**Comment by aptalca** [comment]
Ah, you want to fancy it up. On it.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
