### PR TITLE
Fixes workflow links for actions

### PR DESCRIPTION
**Pull request by IronicBadger**
Fixed broken links for Github workflow actions.

### CODE REVIEW

**Review by nemchik — APPROVED** [review]

**Review by nemchik — CHANGES_REQUESTED** [review]
Sorry I meant to request changes. This needs to be applied to https://github.com/linuxserver/docker-jenkins-builder/blob/master/roles/generate-jenkins/templates/greetings.j2

**Comment by IronicBadger** [comment]
Ok no prob. I'll do that in a few.

**Comment by IronicBadger** [comment]
@nemchik done!

**Review by nemchik — APPROVED** [review]
LGTM. I don't have merge powers here though.

**Pull request merged**
